# permissions for end users to edit multiclusterservicepolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: multiclusterservicepolicy-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: multicluster-service-policy-controller
    app.kubernetes.io/part-of: multicluster-service-policy-controller
    app.kubernetes.io/managed-by: kustomize
  name: multiclusterservicepolicy-editor-role
rules:
- apiGroups:
  - example.com.example.com
  resources:
  - multiclusterservicepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.com.example.com
  resources:
  - multiclusterservicepolicies/status
  verbs:
  - get
